---
title: "Clustering Analysis 2"
author: "Anwesha Guha"
date: '2023-05-18'
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    highlight: tango
    code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(pacman)
p_load(here, purrr, tidyverse, ggcorrplot, proxy, plotly, patchwork, psych, GPArotation, parameters, DT, nFactors)
source(here("scripts/branding.R"))
load(here("data/complete_canopy_2023.RData"))

c4 <- read_tsv(here("output/EFA 2023 Results All.txt"))
```

# Cluster Descriptives

Note: Much of this is adapted from Gregor's code (see 2022 canopy for details).

```{r}
cweights <- c4 %>% 
#  rename(all_of(clust_details_r)) %>%
  select(-Complexity, -Uniqueness) %>%
  pivot_longer(cols = -Variable, names_to = "cluster", values_to = "weight") %>%
  rename(practice = Variable)

practices_long <- tags %>% 
  select(school_id, starts_with("practices")) %>%
  pivot_longer(-school_id, names_to = "practice", values_to = "val")

clusters_by_school <- practices_long %>%
  left_join(cweights, by = "practice") %>%
  group_by(school_id, cluster) %>% 
  summarize(cluster_weight = sum(val * weight, na.rm = TRUE), .groups = "drop") %>%
  arrange(school_id) 

clusters_by_school_wide <- clusters_by_school %>%
  pivot_wider(id_cols = school_id, names_from = cluster, values_from = cluster_weight) %>%
  arrange(school_id) %>% 
  rename(learning_mastery = MR1,
         holistic_student_justice = MR2,
         postsec_pathways_world = MR3,
         blended_flexible_learning = MR4)

update = FALSE

if(update) {
  write_tsv(clusters_by_school, file = here("data/cluster_scores_by_school_long.tsv"))
  write_tsv(clusters_by_school_wide, file = here("data/cluster_scores_by_school_wide.tsv"))
}
```


```{r}

interfactor_cor = cor(clusters_by_school_wide[-1])

interfactor_cor %>%
  datatable(
    caption = "Intercluster Correlations"
  ) %>%
  formatRound(digits = 2, columns = colnames(interfactor_cor))
```

```{r}
ggcorrplot(interfactor_cor, lab = T, type = "upper", hc.order = TRUE) +
  scale_fill_distiller(type = "div", limits = c(0, 1), expand = c(0, 0)) +
    labs(title = "Correlation between clusters",
         fill = "Correlation") +
#    scale_x_discrete(labels = clust_labs) +
 #   scale_y_discrete(labels = clust_labs) +
    labs(x = "", y = "") + 
#    scale_fill_cc_gradient + 
    theme_transcend_sparse + 
    theme(axis.text.x = element_text(angle = 35, hjust = 1, vjust = 1, size = rel(0.6)), 
          axis.text.y = element_text(size = rel(0.6)),
          panel.border = element_blank(),
          axis.ticks = element_blank()
          )

```


```{r}
ggplot(clusters_by_school, aes(x = cluster, y = cluster_weight)) +
  geom_violin(fill = transcend_cols[2]) +
  geom_point(
    color = transcend_cols[3],
    position = position_jitter(width = 0.2),
    size = 0.2
  ) +
#  scale_x_discrete(labels = clust_labs) +
  labs(
    x = "", y = "Weight",
    title = "Distribution of cluster weights"
  ) +
  theme(axis.text.x = element_text(angle = 35, hjust = 1, vjust = 1, size = rel(0.5)))
```

# Cluster Associations with Leaps

## Ranks

```{r echo=TRUE, fig.width=10, message=FALSE}
leaps_ranks <- full %>%
  select(school_id, starts_with("leaps_rank")) %>%
  arrange(school_id) %>% 
  select(-school_id)


leaps_clusters <- cor(leaps_ranks, 
  clusters_by_school_wide %>% 
  select(-school_id),
  method = "spearman"
)

ggcorrplot(leaps_clusters, hc.order = FALSE, lab = TRUE, lab_size = 2) +
    scale_fill_distiller(type = "div", limits = c(-1, 1), expand = c(0, 0)) +
    labs(title = "Correlation between practice clusters\nand leaps ranks",
         fill = "Correlation") +
    #scale_x_discrete(labels = label_tags) +
    #scale_y_discrete(labels = label_tags) +
    labs(x = "", y = "") + 
    #scale_fill_cc_gradient + 
    theme_transcend_sparse + 
#    scale_y_discrete(labels = label_clust) +
    theme(
      axis.text.x = element_text(angle = 35, hjust = 1, vjust = 1, size = rel(0.8)),
      axis.text.y = element_text(size = rel(0.8)),
      panel.border = element_blank(),
      axis.ticks = element_blank()
    )
```


```{r echo=TRUE}
leaps_clusters %>% 
  datatable(
    caption = "Leap Ranks and Clusters Correlations"#,
    #colnames = c("Jaccard (0,1)" = "jaccard", "Correlation (-1,1)" = "correlation")
  ) %>%
  formatRound(digits = 2, columns = colnames(leaps_clusters)) 
```
## Leaps Variables

```{r echo=TRUE, fig.height=8, fig.width=10, message=FALSE}
leaps_vars <- full %>%
  select(school_id, starts_with("leaps_")) %>% 
  select(-starts_with("leaps_rank")) %>%
  arrange(school_id) 


leapsv_clusters <- cor(
  leaps_vars %>% select(-school_id) %>% mutate(across(everything(), \(x) x != "0")),
  clusters_by_school_wide %>% select(-school_id)
)

ggcorrplot(leapsv_clusters, lab = TRUE, lab_size = 2) +
    scale_fill_distiller(type = "div", limits = c(-1, 1), expand = c(0, 0)) +
    labs(title = "Correlation between practice clusters\nand leaps variables",
         fill = "Correlation") +
    #scale_x_discrete(labels = label_tags) +
    #scale_y_discrete(labels = label_tags) +
    labs(x = "", y = "") + 
    #scale_fill_cc_gradient + 
    theme_transcend_sparse + 
#    scale_y_discrete(labels = label_clust) +
    theme(
      axis.text.x = element_text(angle = 35, hjust = 1, vjust = 1, size = rel(0.8)),
      axis.text.y = element_text(size = rel(0.8)),
      panel.border = element_blank(),
      axis.ticks = element_blank()
    )

leapsv_clusters %>%
  datatable(
    caption = "Leaps Variables and Clusters Correlations"#,
  ) %>%
  formatRound(digits = 2, columns = colnames(leaps_clusters)) 
```

# Cluster Associations with Demographics

```{r}
features_df <- read_rds(here("data/features_for_models.rds"))

feature_names <- c("school_id", "grades_prek", "grades_elementary", "grades_middle", "grades_high", "urban", "suburban", "rural", "school_descriptor", "leadership_diversity", "teaching_diversity", "scaled_self_reported_ell", "scaled_self_reported_frpl", "scaled_self_reported_swd", "scaled_self_reported_total_enrollment", "scaled_self_reported_bipoc")

response_names <- c(
  "Deeper learning for mastery", 
  "Educational justice and holistic student support", 
  "Postsecondary pathways and the world outside school", 
  "Flexible, blended and individualized learning pathways" 
)

clust_labs <- c("learning_mastery", "holistic_student_justice", "postsec_pathways_world", "blended_flexible_learning")

model_data <-
  inner_join(clusters_by_school_wide, features_df, by = "school_id") %>%
  mutate(across(all_of(clust_labs), scale))# %>%
#  rename(set_names(clust_labs, response_names))

formulas = sprintf("%s ~ %s", clust_labs, paste(feature_names, collapse = " + "))
```

```{r fit_models, eval=FALSE, message=FALSE, cache=TRUE, include=FALSE}
library(rstanarm)

mods = list()

for(i in seq_along(formulas)) {
  message("\n\n\nSTARTING MODEL ", i, " OF ", length(formulas), "\n\n\n")
  mods[[clust_labs[i]]] = stan_lm(
    formulas[i],
    data = model_data,
    prior = R2(location = 0.3)
  )
}
```

```{r report_models, eval=FALSE, fig.height=, fig.width=15, include=FALSE}

library(broom.mixed)
mods %>% map_df(tidy, .id = "response") %>% 
    filter(!term %in% c("(Intercept)")) ->
  coef_df
    
# coef_labeler = function(x) {
#   x %>% 
#     str_replace(pattern = "diversity_staff", "Staff: ") %>%
#     str_replace(pattern = "diversity_leads", "Leadership: ") %>%
#     str_replace("_scaled", "") %>%
#     str_replace("grades_", "Level: ") %>%
#     str_replace("schooL_descriptor_", "Type: ") %>%
#     str_replace("locale", "Locale: ") %>%
#     str_replace("n_students", "Number of students") %>%
#     label_dems
# }


ggplot(
  coef_df, 
  aes(x = estimate, y = fct_reorder(term, estimate, .fun = mean))
) + 
  geom_col(fill = transcend_cols[2]) + 
  geom_errorbarh(aes(xmin = estimate - std.error, xmax = estimate + std.error), height = 0.2) +
  labs(y = "",
       x = "Average change in cluster score (in standard deviations)", 
       title = "Association between school characteristics and practice clusters",
       subtitle = "NOTE: Error bars show 65% confidence intervals.") +
  guides(fill = FALSE) +
  facet_grid(~ response) + 
#  scale_y_discrete(labels = coef_labeler) + 
  theme(#axis.text = element_text(size = 8), strip.text = element_text(size = rel(0.6)),
        panel.grid.major.y = element_blank()#,
        #axis.text.x = element_text(angle = -90, vjust = 0.5, hjust = 0)
      ) 
```


# Cluster Associations with School Type
```{r echo=TRUE, fig.width=10, message=FALSE}

clusters_by_school2 <- practices_long %>%
  left_join(cweights, by = "practice") %>%
  group_by(school_id, cluster) %>% 
  summarize(cluster_weight = sum(val * weight, na.rm = TRUE), .groups = "drop") %>%
  arrange(school_id) %>% 
  mutate(cluster = case_when(cluster == "MR1" ~ "learning mastery",
                             cluster == "MR2" ~ "holistic student justice",
                             cluster == "MR3" ~ "postsecondary pathways",
                             cluster == "MR4" ~ "blended flexible learning"))  

school_type <- full %>% 
  select(school_id, school_descriptor) %>% 
  mutate(school_descriptor = case_when(school_descriptor == 1 ~ "Public district",
                                       school_descriptor == 2 ~ "Public charter",
                                       school_descriptor == 3 ~ "Independent private"))

school_type <- left_join(clusters_by_school2, school_type)

ggplot(school_type, aes(x = cluster, y = cluster_weight)) +
  geom_violin(fill = transcend_cols[2]) +
  geom_point(
    color = transcend_cols[3],
    position = position_jitter(width = 0.2),
    size = 0.2
  ) +
  facet_wrap(~school_descriptor) +
  labs(
    x = "", y = "Weight",
    title = "Distribution of cluster weights"
  ) +
  theme(axis.text.x = element_text(angle = 35, hjust = 1, vjust = 1, size = rel(0.5)))

```


# Cluster Mutations for retreat

```{r}
practices_cor <- tags %>%
  select(starts_with("practices")) %>%
  cor

efa_4 <- fa(practices_cor, nfactors = 4, rotate = "oblimin", fm = "minres")

c4_max <- efa_4 %>% 
  model_parameters(sort = TRUE, threshold = "max") %>% 
  select(-c(6:7))
```


```{r}
clust <- left_join(c4_max, tag_labels, by = join_by(Variable == tag))

clust[is.na(clust)] <- 0

clust2 <- clust %>% 
  mutate(cluster = case_when(MR2 != 0 ~ "holistic student justice",
                             MR3 != 0 ~ "postsecondary pathways",
                             MR4 != 0 ~ "blended flexible learning",
                             MR1 != 0 ~ "learning mastery"))
```


```{r}
clust_prep <- full %>% 
  select(school_id, starts_with("practices_")) %>% 
  pivot_longer(cols = c(starts_with("practices")),
               names_to = "tag",
               values_to = "value") %>% 
  filter(value>0)

clust_prep <- clust_prep %>% 
  group_by(tag) %>% 
  summarise(sum = n())

clust_count <- left_join(clust2, clust_prep, by = join_by(Variable ==tag)) %>% 
  select(6:8)
```

```{r}
clust_count
```



