---
title: "Clustering Analysis"
author: "Anwesha Guha"
date: '2023-05-01'
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    highlight: tango
    code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(here, purrr, tidyverse, ggcorrplot, proxy, plotly, patchwork, psych, GPArotation, parameters, DT, nFactors)
source(here("scripts/branding.R"))
# Error in source(here("scripts/branding.R")) : 
#   /Users/aguha/Documents/r_projects/canopy-dac-23/scripts/branding.R:77:3: unexpected string constant
# 76:   "Other Geographic Locale" = "self_reported_locale_other"
# 77:   "Homeschools"
load(here("data/complete_canopy_2023.RData"))
```

# Correlations

First we calculate a correlation matrix for the tags.

```{r, message=FALSE}
practices_cor <- tags %>%
  select(starts_with("practices")) %>%
  cor

practices_jac <- tags %>%
  select(starts_with("practices")) %>%
  simil(method = "Jaccard", by_rows = FALSE)

plot_tag_cor <- function(cor_mat, title = "") {
  ggcorrplot(cor_mat, hc.order = T, type = "upper") +
    scale_fill_distiller(type = "div", limits = c(-1, 1), expand = c(0, 0)) +
    labs(title = title,
         fill = "Correlation") +
    #scale_x_discrete(labels = label_tags) +
    #scale_y_discrete(labels = label_tags) +
    labs(x = "", y = "") + 
    #scale_fill_cc_gradient + 
#    theme_transcend_sparse + 
    theme(axis.text.x = element_blank(), 
          axis.text.y = element_blank(),
          panel.border = element_blank(),
          axis.ticks = element_blank()
          )
}
```

```{r, message=FALSE}
cor_plot <- plot_tag_cor(practices_cor, 
                         title = "Correlation heat map for all tags") +
            theme(legend.position = c(.85, .25))

ggplotly(cor_plot)
```

```{r, message=FALSE}
jac_plot <- plot_tag_cor(as.matrix(practices_jac), 
                         title = "Jaccard similarity for all tags") +
  theme(legend.position = c(.85, .25)) + 
  scale_fill_distiller(type = "div", limits = c(0, 1), expand = c(0, 0))

ggplotly(jac_plot)
```

```{r, message=FALSE}
mat_to_df <- function(m) {
  data.frame(row=rownames(m)[row(m)[upper.tri(m)]], 
           col=colnames(m)[col(m)[upper.tri(m)]], 
           corr=m[upper.tri(m)])
}

d_corr <- mat_to_df(practices_cor)
d_jacc <- mat_to_df(as.matrix(practices_jac))

jacc_corr <- d_jacc %>%
  rename(jaccard = corr) %>%
  left_join(d_corr, by = c("row", "col")) %>%
  rename(correlation = corr) %>%
  mutate(
    jacc_rank = rank(-jaccard),
    corr_rank = rank(-correlation),
    rank_diff = jacc_rank - corr_rank
  ) %>% 
  arrange(desc(jaccard))

jacc_corr %>% 
  datatable(
    caption = "Comparison of Jaccard Similarity and Correlation Coeffficients",
    colnames = c("Jaccard (0,1)" = "jaccard", "Correlation (-1,1)" = "correlation")
  ) %>%
  formatRound(digits = 2, columns = c("Jaccard (0,1)", "Correlation (-1,1)")) 
```


```{r, fig.width = 12}
corr_hist <- ggplot(jacc_corr, aes(x = correlation)) +
  geom_histogram(binwidth = 0.03 #, fill = transcend_cols["blue"]
                 ) +
  geom_vline(aes(xintercept = mean(correlation)), 
             #color = transcend_cols["red"], 
             size = 1) +
  geom_text(aes(x = mean(correlation), y = Inf, 
                label = paste("Average:",round(mean(correlation), 2))), 
            hjust = -.1, check_overlap = TRUE, vjust = 1.1, 
            family = "Open Sans") + 
#  bar_y_scale_count +
  scale_x_continuous(limits = c(-1, 1), expand = expansion(0, 0)) +
  labs(title = "Distribution of pairwise tag correlations", 
       y = "Count of Tag Pairs",
       x = "Correlation") +
  theme(plot.margin = margin(t = 8, r = 12, b = 8, l = 8, unit = "pt")) +
  theme_minimal()

jacc_hist <- ggplot(jacc_corr, aes(x = jaccard)) +
  geom_histogram(binwidth = 0.03 #, fill = transcend_cols["teal"]
                 ) +
  geom_vline(aes(xintercept = mean(jaccard)), 
             #color = transcend_cols["red"], 
             size = 1) +
  geom_text(aes(x = mean(jaccard), y = Inf, 
                label = paste("Average:", round(mean(jaccard), 2))), 
            hjust = -.1, check_overlap = TRUE, vjust = 1.1, 
            family = "Open Sans") + 
#  bar_y_scale_count +
  scale_x_continuous(limits = c(0, 1), expand = expansion(0, 0)) +
  labs(title = "Distribution of pairwise tag similarities", 
       y = "Count of Tag Pairs",
       x = "Jaccard Similarity") +
  theme(plot.margin = margin(t = 8, r = 12, b = 8, l = 8, unit = "pt")) +
  theme_minimal()

corr_hist + jacc_hist
```

# Clustering

## Scree Plots

```{r}
fa_cor <- fa.parallel(
  practices_cor, fm = "pa", fa = "fa", n.obs = nrow(tags),
  main = "Correlation scree plot"
)
```

```{r}
jac_mat <- as.matrix(practices_jac)
jac_mat[is.na(jac_mat)] = 1

fa_jac <- fa.parallel(jac_mat, fm = "pa", fa = "fa", 
                      n.obs = nrow(tags),
                      main = "Jaccard scree plot"
)
```

## Parallel Analysis

```{r}
# n_i  <- nrow(values_3) # The number of cases in our data
# n_p <- ncol(values_3) # The number of variables in our data
# 
# set.seed(2)   # To reproduce our randomly generated results.
# 
# Eigs <- pca_3$values    # The eigenvalues
# n_components  <- length(Eigs) # number of components
# 
# paral <- parallel(subject = n_i,  # The number of cases in our data
#                   var = n_p,  # The number of variables in our data
#                   rep = 1000,
#                   quantile = .95,
#                    model  = "components")
# 
# ParallelAna <- data.frame(Ncomponent  = 1:n_components,
#                            Eigs,
#                            RandEigM = paral$eigen$mevpea,
#                            RandEig95= paral$eigen$qevpea)
# 
# ParallelAna <- round(ParallelAna, 3)
# ParallelAna
```

```{r}
# exceeder <- ParallelAna[ParallelAna[, "RandEig95"] > ParallelAna[, "Eigs"], ][1,]
# exceeder
```

## Retaining 3 clusters

```{r, include=FALSE}
## retain 3 clusters
# promax vs oblimin rotations?
efa_2023 <- fa(practices_cor, nfactors = 3, rotate = "oblimin", fm = "minres")

## all the junk that prints is well-explained here: https://m-clark.github.io/posts/2020-04-10-psych-explained/
print(efa_2023, sort = T)

write_efa_files <- function(efa, dir, file, threshold = 0.28) {
  efa %>%
    model_parameters(sort = TRUE, threshold = "max") %>%
    write_tsv(here(dir, paste(file, "Max.txt")), na = "")
  efa %>%
    model_parameters(sort = TRUE, threshold = threshold) %>%
    write_tsv(here(dir, paste(file, "Threshold.txt")), na = "")
  efa %>%
    model_parameters(sort = TRUE) %>%
    write_tsv(here(dir, paste(file, "All.txt")), na = "")
  invisible()
}

print_efa <- function(
  efa, 
  type = c("max", "threshold", "all"), 
  threshold = 0.28, #check this threshold
  caption = "")
{
  type = match.arg(type)
  if(type == "max") {
    return(efa |> 
      model_parameters(sort = TRUE, threshold = "max") |>
      datatable(caption = paste(caption, "Max loadings")) |>
      formatRound(digits = 2, columns = 2:(efa$factors + 3)))
  }
  if(type == "threshold") {
    return(efa |> 
      model_parameters(sort = TRUE, threshold = threshold) |>
      datatable(caption = paste(caption, "Threshold loadings")) |>
      formatRound(digits = 2, columns = 2:(efa$factors + 3)))
  }
  if(type == "all") {
    return(efa |> 
      model_parameters(sort = TRUE) |>
      datatable(caption = paste(caption, "All loadings")) |>
      formatRound(digits = 2, columns = 2:(efa$factors + 3)))
  }
}
```

```{r}
efa_2023 %>%
  model_parameters(sort = TRUE, threshold = "max") %>%
  write_tsv(here("output", "EFA 2023 Results Max.txt"), na = "") %>%
  datatable(caption = "Max loadings") %>%
  formatRound(digits = 2, columns = 2:8) 
```

```{r}
efa_2023 %>%
  model_parameters(sort = TRUE, threshold = 0.28) %>%
  write_tsv(here("output", "EFA 2023 Results Threshold.txt"), na = "") %>%
  datatable(caption = "Threshold loadings") %>%
  formatRound(digits = 2, columns = 2:8) 
```

```{r}
efa_2023 %>%
  model_parameters(sort = TRUE) %>%
  write_tsv(here("output", "EFA 2023 Results All.txt"), na = "") %>%
  datatable(caption = "All loadings") %>%
  formatRound(digits = 2, columns = 2:8) 

# Warning message included below, just in case:
# DataTables warning: table id=DataTables_Table_0 - Requested unknown parameter '7' for row 0, column 7. For more information about this error, please see http://datatables.net/tn/4
```